/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdad3",
        "ink-700": "#333333",
        "secondary": "#5f5e5e",
        "on-primary-fixed": "#001158",
        "primary": "#0032c4",
        "error": "#ba1a1a",
        "secondary-container": "#e5e2e1",
        "surface-container-highest": "#e2e1f0",
        "on-primary-container": "#d2d7ff",
        "on-primary-fixed-variant": "#0032c3",
        "inverse-surface": "#2e303b",
        "conf-unverified": "#888888",
        "on-secondary-fixed": "#1c1b1b",
        "on-background": "#191b25",
        "ink-50": "#F7F7F7",
        "admin-border": "#2A2A2A",
        "primary-fixed-dim": "#b9c3ff",
        "on-surface": "#191b25",
        "ink-400": "#888888",
        "admin-surface": "#161616",
        "inverse-on-surface": "#f0effe",
        "surface-bright": "#fbf8ff",
        "inverse-primary": "#b9c3ff",
        "ink-100": "#EFEFEF",
        "status-escalated": "#DC6803",
        "ink-900": "#0A0A0A",
        "conf-community": "#CA8A04",
        "secondary-fixed-dim": "#c9c6c5",
        "tertiary-fixed-dim": "#ffb4a4",
        "on-tertiary-fixed-variant": "#8c1800",
        "surface-tint": "#0044fe",
        "on-error-container": "#93000a",
        "primary-fixed": "#dee1ff",
        "background": "#fbf8ff",
        "tertiary-container": "#b72402",
        "surface-variant": "#e2e1f0",
        "surface-dim": "#d9d9e7",
        "on-secondary-container": "#656464",
        "surface-container": "#edecfb",
        "ink-200": "#C8C8C8",
        "surface-container-low": "#f3f2ff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "status-open": "#AAAAAA",
        "status-resolved": "#16A34A",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#3d0600",
        "on-error": "#ffffff",
        "surface-container-high": "#e7e7f5",
        "outline": "#747688",
        "status-discuss": "#E8A000",
        "secondary-fixed": "#e5e2e1",
        "blue-100": "#E6EEFF",
        "on-surface-variant": "#434657",
        "tertiary": "#8d1800",
        "blue-600": "#0033CC",
        "admin-bg": "#0D0D0D",
        "outline-variant": "#c4c5da",
        "surface": "#fbf8ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#0044ff",
        "conf-high": "#16A34A",
        "on-tertiary-container": "#ffcec3",
        "status-verifying": "#0044FF",
        "on-secondary-fixed-variant": "#474646"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-margin": "24px",
        "header-height": "56px",
        "sidebar-width": "224px",
        "content-max-width": "720px",
        "gutter": "16px"
      },
      fontFamily: {
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label-mono": ["IBM Plex Mono", "monospace"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["DM Serif Display", "serif"],
        "display-lg": ["DM Serif Display", "serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-mono": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "400"}],
        "display-lg": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
